# Generated by Django 2.2.12 on 2022-07-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
    ]
